# Site settings
title: BryanWP 
email: bwp.pearson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    System Engineer at ReverbNation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  resnostyle

# Build settings
markdown: kramdown

#Rakefile configs
post:
  template: _post.txt
  extension: markdown
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
